// Code generated by scripts/gen_apps/main.go
//go:build eval && !realistic && !synthetic_small && !synthetic_medium && synthetic_large

package blueprint_apps

import (
	specs_synthetic_app5 "github.com/blueprint-uservices/blueprint/examples/synthetic_app5/wiring/specs"
	"github.com/blueprint-uservices/blueprint/plugins/cmdbuilder"
	"github.com/sirupsen/logrus"
)

func init() {
	cfg, err := loadAppsConfig("registry/apps_synthetic_large.yaml")
	if err != nil {
		logrus.Fatalf("failed to load apps config: %s", err)
	}
	initAppsFromConfig(cfg)
}

func resolveSpec(name string) cmdbuilder.SpecOption {
	switch name {
	case "synthetic_app5_docker":
		return specs_synthetic_app5.Docker
	default:
		logrus.Fatalf("unknown spec name: %s", name)
		return cmdbuilder.SpecOption{}
	}
}
