// Code generated by scripts/gen_apps/main.go
//go:build !eval

package blueprint_apps

import (
	specs_digota "github.com/blueprint-uservices/blueprint/examples/digota/wiring/specs"
	specs_dsb_hotel2 "github.com/blueprint-uservices/blueprint/examples/dsb_hotel2/wiring/specs"
	specs_dsb_mediamicroservices "github.com/blueprint-uservices/blueprint/examples/dsb_mediamicroservices/wiring/specs"
	specs_dsb_socialnetwork "github.com/blueprint-uservices/blueprint/examples/dsb_socialnetwork/wiring/specs"
	specs_eshopmicroservices "github.com/blueprint-uservices/blueprint/examples/eshopmicroservices/wiring/specs"
	specs_postnotification "github.com/blueprint-uservices/blueprint/examples/postnotification/wiring/specs"
	specs_sockshop "github.com/blueprint-uservices/blueprint/examples/sockshop/wiring/specs"
	specs_trainticket "github.com/blueprint-uservices/blueprint/examples/trainticket/wiring/specs"
	"github.com/blueprint-uservices/blueprint/plugins/cmdbuilder"
	"github.com/sirupsen/logrus"
)

func init() {
	cfg, err := loadAppsConfig("registry/apps.yaml")
	if err != nil {
		logrus.Fatalf("failed to load apps config: %s", err)
	}
	initAppsFromConfig(cfg)
}

func resolveSpec(name string) cmdbuilder.SpecOption {
	switch name {
	case "postnotification_docker":
		return specs_postnotification.Docker
	case "digota_docker":
		return specs_digota.Docker
	case "eshopmicroservices_docker":
		return specs_eshopmicroservices.Docker
	case "dsb_mediamicroservices_docker":
		return specs_dsb_mediamicroservices.Docker
	case "sockshop_docker":
		return specs_sockshop.Docker
	case "dsb_socialnetwork_docker":
		return specs_dsb_socialnetwork.Docker
	case "dsb_hotel2_original":
		return specs_dsb_hotel2.Original
	case "trainticket_docker":
		return specs_trainticket.Docker
	default:
		logrus.Fatalf("unknown spec name: %s", name)
		return cmdbuilder.SpecOption{}
	}
}
