// Code generated by scripts/gen_apps/main.go
//go:build eval && !realistic && synthetic_small && !synthetic_medium && !synthetic_large

package blueprint_apps

import (
	specs_synthetic_app1 "github.com/blueprint-uservices/blueprint/examples/synthetic_app1/wiring/specs"
	specs_synthetic_app2 "github.com/blueprint-uservices/blueprint/examples/synthetic_app2/wiring/specs"
	specs_synthetic_app3 "github.com/blueprint-uservices/blueprint/examples/synthetic_app3/wiring/specs"
	"github.com/blueprint-uservices/blueprint/plugins/cmdbuilder"
	"github.com/sirupsen/logrus"
)

func init() {
	cfg, err := loadAppsConfig("registry/apps_synthetic_small.yaml")
	if err != nil {
		logrus.Fatalf("failed to load apps config: %s", err)
	}
	initAppsFromConfig(cfg)
}

func resolveSpec(name string) cmdbuilder.SpecOption {
	switch name {
	case "synthetic_app1_docker":
		return specs_synthetic_app1.Docker
	case "synthetic_app2_docker":
		return specs_synthetic_app2.Docker
	case "synthetic_app3_docker":
		return specs_synthetic_app3.Docker
	default:
		logrus.Fatalf("unknown spec name: %s", name)
		return cmdbuilder.SpecOption{}
	}
}
