// Package blueprint_apps loads registry/apps.yaml and maps each registered application to its code
// and wiring spec (apps.go is generated by scripts/gen_app_registry)
package blueprint_apps

import (
	"os"
	"path/filepath"
	"sort"

	"github.com/blueprint-uservices/blueprint/plugins/cmdbuilder"
	"gopkg.in/yaml.v2"

	"analyzer/pkg/utils"
)

type AppConfig struct {
	Name        string   `yaml:"name"`
	AppRoot     string   `yaml:"app_root"`
	PackagePath string   `yaml:"package_path"`
	SpecName    string   `yaml:"spec_name"`
	SpecPath    string   `yaml:"spec_path"`
	SQLTables   []string `yaml:"sql_tables"`
	NoSQLPath   string   `yaml:"nosql_path"`
}

type AppsConfig struct {
	Apps []AppConfig `yaml:"apps"`
}

type AppInfo struct {
	PackagePath   string
	BlueprintSpec cmdbuilder.SpecOption
}

var APPS_INFO = map[string]AppInfo{}
const BLUEPRINT_EXAMPLES_PKG_PREFIX    = "github.com/blueprint-uservices/blueprint/examples/"

// AppNames returns the sorted names of the apps that can be analyzed
func AppNames() []string {
	names := make([]string, 0, len(APPS_INFO))
	for name := range APPS_INFO {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func loadAppsConfig(path string) (*AppsConfig, error) {
	data, err := os.ReadFile(resolveFromAncestors(path))
	if err != nil {
		return nil, err
	}
	var cfg AppsConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// resolveFromAncestors returns the first existing path/relpath found when walking up from the
// working directory, so that the registry is found when running from a package directory
// (e.g., `go test ./pkg/...`); falls back to relpath unchanged
func resolveFromAncestors(relpath string) string {
	dir, err := os.Getwd()
	if err != nil {
		return relpath
	}
	for {
		candidate := filepath.Join(dir, relpath)
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return relpath
		}
		dir = parent
	}
}

func initAppsFromConfig(cfg *AppsConfig) {
	for _, app := range cfg.Apps {
		if app.PackagePath != "" {
			var spec cmdbuilder.SpecOption
			if app.SpecName != "" {
				spec = resolveSpec(app.SpecName)
			}
			APPS_INFO[app.Name] = AppInfo{
				PackagePath:   app.PackagePath,
				BlueprintSpec: spec,
			}
			utils.RegisterApp(BLUEPRINT_EXAMPLES_PKG_PREFIX + app.PackagePath)
		}
		if app.NoSQLPath != "" {
			utils.APPS_NOSQL_SCHEMAS[app.Name] = app.NoSQLPath
		}
		if len(app.SQLTables) > 0 {
			utils.APPS_SQL_TABLES[app.Name] = app.SQLTables
		}
	}
}
